import { 
  Code, 
  Smartphone, 
  Palette, 
  ShoppingCart, 
  TrendingUp, 
  Server, 
  Database, 
  Link, 
  FileCode, 
  Puzzle, 
  Shield, 
  Headphones, 
  Zap, 
  CreditCard, 
  MessageCircle, 
  Globe, 
  Cpu, 
  BarChart3, 
  Monitor, 
  Camera, 
  Users, 
  Target, 
  Rocket, 
  Settings, 
  Cloud,
  Layers,
  SmartphoneIcon,
  ShoppingBag,
  BarChart,
  Database2,
  GitBranch,
  Box,
  Globe2,
  ShieldCheck,
  Zap as Lightning,
  Palette as Design,
  Code2,
  Smartphone2,
  TrendingUp2,
  Server2,
  Link2,
  FileCode2,
  Puzzle2,
  Shield2,
  Headphones2,
  Zap2,
  CreditCard2,
  MessageCircle2
} from "lucide-react"

export const services = [
  {
    title: "Custom Software Development",
    description: "Tailored software solutions built with modern technologies to solve your unique business challenges",
    icon: Code,
    features: [
      "Full-stack web applications",
      "API development & integration",
      "Database design & optimization",
      "Cloud deployment & scaling",
      "Performance optimization",
      "Security implementation"
    ],
    color: "from-[#ef3a5d] to-[#ff6b6b]",
    category: "software",
    slug: "custom-software-development",
  },
  {
    title: "Mobile App Development",
    description: "Native and cross-platform mobile applications that deliver exceptional user experiences",
    icon: SmartphoneIcon,
    features: [
      "iOS & Android development",
      "React Native applications",
      "Progressive Web Apps (PWA)",
      "App store optimization",
      "Push notification systems",
      "Offline functionality"
    ],
    color: "from-[#61DAFB] to-[#4ECDC4]",
    category: "software",
    slug: "mobile-app-development",
  },
  {
    title: "UI/UX Design",
    description: "User-centered design that creates intuitive, beautiful, and conversion-focused interfaces",
    icon: Palette,
    features: [
      "User interface design",
      "User experience optimization",
      "Prototyping & wireframing",
      "Design systems creation",
      "Usability testing",
      "Brand identity integration"
    ],
    color: "from-[#F24E1E] to-[#FF6B6B]",
    category: "design",
    slug: "ui-ux-design",
  },
  {
    title: "E-commerce Development",
    description: "Complete online store solutions with payment processing and inventory management",
    icon: ShoppingBag,
    features: [
      "Custom e-commerce platforms",
      "Payment gateway integration",
      "Inventory management systems",
      "Order processing automation",
      "Multi-vendor marketplaces",
      "Mobile commerce optimization"
    ],
    color: "from-[#95BF47] to-[#7CB342]",
    category: "software",
    slug: "ecommerce-development",
  },
  {
    title: "Digital Marketing",
    description: "Strategic marketing campaigns that drive traffic, engagement, and conversions",
    icon: BarChart,
    features: [
      "Search engine optimization (SEO)",
      "Social media marketing",
      "Content marketing strategies",
      "Email marketing campaigns",
      "PPC & Google Ads",
      "Analytics & reporting"
    ],
    color: "from-[#FF6B6B] to-[#FF8E53]",
    category: "marketing",
    slug: "digital-marketing",
  },
  {
    title: "Cloud Solutions",
    description: "Scalable cloud infrastructure and deployment solutions for modern applications",
    icon: Cloud,
    features: [
      "AWS & Azure deployment",
      "Serverless architecture",
      "Container orchestration",
      "Database migration",
      "Load balancing & scaling",
      "Security & compliance"
    ],
    color: "from-[#FF9900] to-[#FF6B6B]",
    category: "software",
    slug: "cloud-solutions",
  },
  {
    title: "API Development",
    description: "Robust and scalable APIs that enable seamless integration between systems",
    icon: Link,
    features: [
      "RESTful API design",
      "GraphQL implementation",
      "API documentation",
      "Authentication & authorization",
      "Rate limiting & caching",
      "API testing & monitoring"
    ],
    color: "from-[#6366F1] to-[#8B5CF6]",
    category: "software",
    slug: "api-development",
  },
  {
    title: "Database Design",
    description: "Optimized database architecture and management for high-performance applications",
    icon: Database2,
    features: [
      "Database schema design",
      "Performance optimization",
      "Data migration",
      "Backup & recovery",
      "Security implementation",
      "Monitoring & maintenance"
    ],
    color: "from-[#10B981] to-[#059669]",
    category: "software",
    slug: "database-design",
  },
  {
    title: "Maintenance & Support",
    description: "Comprehensive technical support and maintenance services to keep your systems running smoothly",
    icon: Shield,
    features: [
      "24/7 technical support",
      "System monitoring",
      "Security updates",
      "Performance optimization",
      "Bug fixes & patches",
      "Regular maintenance"
    ],
    color: "from-[#F59E0B] to-[#D97706]",
    category: "support",
    slug: "maintenance-support",
  }
] 