import { Code, Smartphone, Palette, ShoppingCart, TrendingUp, Server, Database, Link, FileCode, Puzzle, Shield, Headphones, Zap, CreditCard, MessageCircle } from "lucide-react"

export const services = [
  {
    title: "UI/UX Design",
    description: "Professional user interface and experience design services",
    icon: Palette,
    features: [
      "User Interface Design",
      "User Experience Design",
      "Wireframing & Prototyping",
      "Design Systems",
      "Mobile App Design",
      "Web Design",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "design",
    slug: "ui-ux-design",
  },
  {
    title: "Web Development",
    description: "Modern, responsive web applications built with cutting-edge technologies",
    icon: Code,
    features: [
      "React.js & Next.js Development",
      "Node.js & Express.js Backend",
      "Database Design & Integration",
      "RESTful API Development",
      "Authentication & Authorization",
      "Performance Optimization",
      "SEO Implementation",
      "Responsive Design",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "development",
    slug: "web-development",
  },
  {
    title: "Mobile App Development",
    description: "Native and cross-platform mobile applications for iOS and Android",
    icon: Smartphone,
    features: [
      "React Native Development",
      "Flutter Development",
      "iOS App Development",
      "Android App Development",
      "App Store Optimization",
      "Push Notifications",
      "Offline Functionality",
      "Performance Optimization",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "development",
    slug: "mobile-app-development",
  },
  {
    title: "Shopify Development",
    description: "Custom Shopify stores, themes, and app development",
    icon: ShoppingCart,
    features: [
      "Custom Shopify Theme Development",
      "Shopify App Development",
      "Store Setup & Configuration",
      "Payment Gateway Integration",
      "Third-party App Integration",
      "Custom Functionality",
      "Performance Optimization",
      "Store Migration",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "ecommerce",
    slug: "shopify-development",
  },
  {
    title: "WordPress Development",
    description: "Custom WordPress websites, themes, and plugin development",
    icon: Server,
    features: [
      "Custom WordPress Development",
      "Theme Development & Customization",
      "Plugin Development",
      "WooCommerce Integration",
      "Multisite Network Setup",
      "Performance Optimization",
      "Security Implementation",
      "Maintenance & Support",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "cms",
    slug: "wordpress-development",
  },
  {
    title: "Digital Marketing",
    description: "Comprehensive digital marketing strategies and campaigns",
    icon: TrendingUp,
    features: [
      "Social Media Marketing",
      "PPC Campaigns (Google/Facebook)",
      "Email Marketing Campaigns",
      "Content Marketing Strategy",
      "Influencer Marketing",
      "Brand Awareness Campaigns",
      "Lead Generation",
      "Conversion Optimization",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "marketing",
    slug: "digital-marketing",
  },
  {
    title: "API Development & Integration",
    description: "RESTful APIs and third-party service integrations",
    icon: Link,
    features: [
      "RESTful API Development",
      "GraphQL APIs",
      "Third-party Integrations",
      "API Documentation",
      "Authentication & Security",
      "Rate Limiting",
      "API Testing",
      "Microservices Architecture",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "development",
    slug: "api-development-integration",
  },
  {
    title: "Database Design & Management",
    description: "Efficient database architecture and optimization",
    icon: Database,
    features: [
      "Database Design & Architecture",
      "SQL & NoSQL Databases",
      "Data Modeling",
      "Performance Optimization",
      "Data Migration",
      "Backup & Recovery Solutions",
      "Database Security",
      "Scalability Planning",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "development",
    slug: "database-design-management",
  },
  {
    title: "SEO & Analytics",
    description: "Search engine optimization and performance analytics",
    icon: TrendingUp,
    features: [
      "Technical SEO Optimization",
      "On-page & Off-page SEO",
      "Local SEO",
      "Google Analytics Setup",
      "Performance Monitoring",
      "Keyword Research & Strategy",
      "Link Building",
      "SEO Audits & Reports",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "marketing",
    slug: "seo-analytics",
  },
  {
    title: "Progressive Web Apps (PWA)",
    description: "Fast, reliable web applications with native app features",
    icon: Zap,
    features: [
      "Offline Functionality",
      "Push Notifications",
      "App-like Experience",
      "Fast Loading Performance",
      "Responsive Design",
      "Cross-platform Compatibility",
      "Service Workers",
      "Web App Manifest",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "development",
    slug: "progressive-web-apps",
  },
  {
    title: "Payment Gateway Integration",
    description: "Secure payment processing solutions for businesses",
    icon: CreditCard,
    features: [
      "Multiple Payment Methods",
      "Secure Transaction Processing",
      "Recurring Payment Setup",
      "Payment Analytics",
      "Fraud Protection",
      "Mobile Payment Solutions",
      "International Payments",
      "PCI Compliance",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "development",
    slug: "payment-gateway-integration",
  },
  {
    title: "Real-time Applications",
    description: "Live chat, notifications, and real-time data applications",
    icon: MessageCircle,
    features: [
      "Live Chat Systems",
      "Real-time Notifications",
      "WebSocket Integration",
      "Live Data Updates",
      "Collaborative Tools",
      "Video Conferencing",
      "File Sharing Systems",
      "Multi-user Synchronization",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "development",
    slug: "realtime-applications",
  },
  {
    title: "Custom Software Development",
    description: "Tailored software solutions for specific business needs",
    icon: FileCode,
    features: [
      "Business Requirements Analysis",
      "Custom Application Development",
      "Legacy System Modernization",
      "Software Architecture Design",
      "Scalable Solution Development",
      "System Integration Services",
      "Performance Optimization",
      "Maintenance & Support",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "development",
    slug: "custom-software-development",
  },
  {
    title: "System Integration",
    description: "Connecting different systems and platforms seamlessly",
    icon: Puzzle,
    features: [
      "Third-party System Integration",
      "Data Synchronization",
      "Workflow Automation",
      "Legacy System Integration",
      "Cloud Service Integration",
      "API Connections",
      "Data Migration Services",
      "System Optimization",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "enterprise",
    slug: "system-integration",
  },
  {
    title: "Quality Assurance & Testing",
    description: "Comprehensive testing and quality assurance services",
    icon: Shield,
    features: [
      "Manual Testing",
      "Automated Testing",
      "Performance Testing",
      "Security Testing",
      "User Acceptance Testing",
      "Load Testing",
      "Bug Tracking & Reporting",
      "Quality Assurance Reports",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "qa",
    slug: "quality-assurance-testing",
  },
  {
    title: "Support & Maintenance",
    description: "Ongoing support and maintenance for all your digital assets",
    icon: Headphones,
    features: [
      "24/7 Technical Support",
      "Regular Updates & Patches",
      "Bug Fixes & Troubleshooting",
      "Performance Optimization",
      "Backup Services",
      "Security Updates",
      "Feature Enhancements",
      "Technical Consultation",
    ],
    color: "from-[#ef3a5d] to-[#d62f4f]",
    category: "support",
    slug: "support-maintenance",
  },
] 